### ISSUE TITLE
composer require error

### ISSUE THREAD

**Issue by AdeSupriyadi** [nakamichikun/ci-twig-hmvc#1]
C:\Program Files\Apache24\htdocs\ci-master>composer require nakamichikun/ci-twig-hmvc
Using version ^1.0 for nakamichikun/ci-twig-hmvc
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for codeigniter/framework No version set (parsed as 1.0.0) -> satisfiable by codeigniter/framework[No version set (parsed as 1.0.0)].
    - nakamichikun/ci-twig-hmvc v1.0.0 requires codeigniter/framework ^3.1 -> satisfiable by codeigniter/framework[3.1.0, 3.1.1, 3.1.10, 3.1.2, 3.1.3, 3.1.4, 3.1.5, 3.1.6, 3.1.7, 3.1.8, 3.1.9].
    - Can only install one of: codeigniter/framework[3.1.0, No version set (parsed as 1.0.0)].
    - Can only install one of: codeigniter/framework[3.1.1, No version set (parsed as 1.0.0)].
    - Can only install one of: codeigniter/framework[3.1.10, No version set (parsed as 1.0.0)].
    - Can only install one of: codeigniter/framework[3.1.2, No version set (parsed as 1.0.0)].
    - Can only install one of: codeigniter/framework[3.1.3, No version set (parsed as 1.0.0)].
    - Can only install one of: codeigniter/framework[3.1.4, No version set (parsed as 1.0.0)].
    - Can only install one of: codeigniter/framework[3.1.5, No version set (parsed as 1.0.0)].
    - Can only install one of: codeigniter/framework[3.1.6, No version set (parsed as 1.0.0)].
    - Can only install one of: codeigniter/framework[3.1.7, No version set (parsed as 1.0.0)].
    - Can only install one of: codeigniter/framework[3.1.8, No version set (parsed as 1.0.0)].
    - Can only install one of: codeigniter/framework[3.1.9, No version set (parsed as 1.0.0)].
    - Installation request for nakamichikun/ci-twig-hmvc ^1.0 -> satisfiable by nakamichikun/ci-twig-hmvc[v1.0.0].

Installation failed, reverting ./composer.json to its original content.

**Comment by AdeSupriyadi** [comment]
sorry solved by adding this
"version": "3.1.10",
in composer.json

**Comment by andixurniawan** [comment]
Thanks :)
